### ISSUE TITLE
Adding Filters to Meta Looker Config in schema.yml

### ISSUE THREAD

**Issue by sisu-callum** [hubble-data/dbt2looker#7]
**Use Case**: Given that programatic creation of all LookML files is the goal, there are a couple features that could potentially be added in order to give people more flexibility in measure creation. The first one I could think of was filters. Individuals would use filters to calculate measures like Active Users (ex: count_distinct user ids where some sort of flag is true).

The following code is my admitted techno-babble as I don't fully understand pydantic and my python is almost exclusively pandas based.

```
def lookml_dimensions_from_model(model: models.DbtModel, adapter_type: models.SupportedDbtAdapters):
    return [
        {
            'name': column.name,
            'type': map_adapter_type_to_looker(adapter_type, column.data_type),
            'sql': f'${{TABLE}}.{column.name}',
            'description': column.description
            'filter':[measure.name: f'measure.value']

        }
        for column in model.columns.values()
        for filter in column.meta.looker.filters
        if map_adapter_type_to_looker(adapter_type, column.data_type) in looker_scalar_types
    ]


def lookml_measures_from_model(model: models.DbtModel):
    return [
        {
            'name': measure.name,
            'type': measure.type.value,
            'sql': f'${{TABLE}}.{column.name}',
            'description': f'{measure.type.value.capitalize()} of {column.description}',
            **'filter':[measure.name: f'measure.value']**
        }
        for column in model.columns.values()
        for measure in column.meta.looker.measures
        **for filter in column.meta.looker.filters**

    ]
```

Pretty obvious I would imagine that my Python skills are lacking/non-existent (and I have no idea if this would actually work) but this idea would add more functionality for those who want to create more dynamic measures. Here is a bare-bones idea of how it could be configured in dbt

![image](https://user-images.githubusercontent.com/76221764/115161757-0d499800-a065-11eb-9f6f-cf1676798712.png)

Then the output would look something like.

```
  measure: Page views {
    type: count
    sql: ${TABLE}.relevant_field ;;
    description: "Count of something."
    filter: [the_name_of_defined_column: value_of_defined_column]
  }
```

**Comment by owlas** [comment]
@sisu-callum this is definitely needed! Will add to the upcoming release

**Comment by owlas** [comment]
Added in b9e799969aad2930efd1bbc3d01b5a2a77db9d60
